name = "FuseApi"
uuid = "67451fab-d9b0-4aa1-a584-3691f4a673db"
authors = ["KlausC <klausC@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
CStructures = "c9817921-aac3-4215-a82e-d746b8a84f94"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.7"
CStructures = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
